import React, { Component } from "react";
import { Field, reduxForm } from "redux-form";

class StreamCreate extends Component {
  //form field component prop -> function OR imported functional components
  //always receives props object generated BY redux form, for our use
  renderInputField = formProps => {
    // console.log(formProps)
    // pass the formProps.input object as an object of props to input.
    //uses the same k/v pairing
    return (
      <div className="field">
        <label>
          {formProps.label}
          <input {...formProps.input} />
        </label>
      </div>
    );
  };

  render() {
    // console.log(this.props);  // all the many things that redux forms adds to this component
    return (
      <form className=" ui form ">
        <Field
          name="title"
          component={this.renderInputField}
          label="Give it a title"
        />
        <Field
          name="description"
          component={this.renderInputField}
          label="...and a description"
        />
      </form>
    );
  }
}

export default reduxForm({
  form: "streamCreate" //form name- typically give it the file name
})(StreamCreate);
